name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 54.94.248.95
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/wppconnect-server
          git pull origin main
          yarn install
          docker-compose down
          docker-compose up -d
